version: "3.5"

services:
  sim:
    image: $SHAPER
    container_name: sim
    hostname: sim
    stdin_open: true
    tty: true
    volumes:
      - $LOG_PATH_SHAPER:/logs/
    env_file: 
      - shaper.env
    cap_add: 
      - NET_ADMIN
    expose:
      - "57832"
    networks:
      leftnet:
        ipv4_address: 193.167.0.2
        ipv6_address: fd00:cafe:cafe:0::2
      rightnet:
        ipv4_address: 193.167.100.2
        ipv6_address: fd00:cafe:cafe:100::2
    extra_hosts:
      - "server:193.167.100.100"

  tcpdump_leftnet:
    image: kaazing/tcpdump
    container_name: vegvisir_tcpdump_leftnet
    stdin_open: true
    tty: true
    depends_on:
      - sim
    cap_add:
      - NET_ADMIN
    volumes:
      - $LOG_PATH_SHAPER:/logs/
    network_mode: "container:sim"
    command: ["-v", "--interface", "eth0", "--packet-buffered", "-w", "/logs/tcpdump_leftnet.pcap" ]

  tcpdump_rightnet:
    image: kaazing/tcpdump
    container_name: vegvisir_tcpdump_rightnet
    stdin_open: true
    tty: true
    depends_on:
      - sim
    cap_add:
      - NET_ADMIN
    volumes:
      - $LOG_PATH_SHAPER:/logs/
    network_mode: "container:sim"
    command: ["-v", "--interface", "eth1", "--packet-buffered", "-w", "/logs/tcpdump_rightnet.pcap" ]

  server:
    image: $SERVER
    container_name: server
    hostname: server
    stdin_open: true
    tty: true
    volumes:
      - $WWW:/www:ro
      - $CERTS:/certs:ro
      - $LOG_PATH_SERVER:/logs/
    env_file: 
      - server.env
    depends_on:
      - sim
    cap_add: 
      - NET_ADMIN
    ulimits:
      memlock: 67108864
    networks:
      rightnet:
        ipv4_address: 193.167.100.100
        ipv6_address: fd00:cafe:cafe:100::100

  client:
    image: $CLIENT
    container_name: client
    hostname: client
    stdin_open: true
    tty: true
    volumes:
      - $DOWNLOAD_PATH_CLIENT:/downloads:delegated
      - $CERTS:/certs:ro
      - $LOG_PATH_CLIENT:/logs/
    env_file: 
      client.env
    depends_on:
      - sim
    cap_add: 
      - NET_ADMIN
    ulimits:
      memlock: 67108864
    networks:
      leftnet:
        ipv4_address: 193.167.0.100
        ipv6_address: fd00:cafe:cafe:0::100
    extra_hosts:
      - "server4:193.167.100.100"
      - "server6:fd00:cafe:cafe:100::100"
      - "server46:193.167.100.100"
      - "server46:fd00:cafe:cafe:100::100"

  iperf_server:
    image: martenseemann/quic-interop-iperf-endpoint
    container_name: iperf_server
    stdin_open: true
    tty: true
    environment:
      - ROLE=server
      - CLIENT=client4
      - IPERF_CONGESTION=$IPERF_CONGESTION
    depends_on:
      - sim
    cap_add: 
      - NET_ADMIN
    networks:
      rightnet:
        ipv4_address: 193.167.100.110
        ipv6_address: fd00:cafe:cafe:100::110
    extra_hosts:
      - "client4:193.167.0.90"
      - "client6:fd00:cafe:cafe:0::100"
      - "client46:193.167.0.90"
      - "client46:fd00:cafe:cafe:0::100"

  iperf_client:
    image: martenseemann/quic-interop-iperf-endpoint
    container_name: iperf_client
    stdin_open: true
    tty: true
    environment:
      - ROLE=client
      - IPERF_CONGESTION=$IPERF_CONGESTION
    depends_on:
      - sim
    cap_add: 
      - NET_ADMIN
    networks:
      leftnet:
        ipv4_address: 193.167.0.90
        ipv6_address: fd00:cafe:cafe:0::90
    extra_hosts:
      - "server4:193.167.100.110"
      - "server6:fd00:cafe:cafe:100::110"
      - "server46:193.167.100.110"
      - "server46:fd00:cafe:cafe:100::110"

networks:
  leftnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
    enable_ipv6: true
    ipam:
      config:
        - subnet: 193.167.0.0/24
        - subnet: fd00:cafe:cafe:0::/64
  rightnet:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.enable_ip_masquerade: 'false'
    enable_ipv6: true
    ipam:
      config:
        - subnet: 193.167.100.0/24
        - subnet: fd00:cafe:cafe:100::/64