#!/bin/bash

if [[ -z "$1" ]]; then
	echo "usage: simple latency(ms) bandwidth(Mbit)"
	exit 1
fi

if [[ -z "$2" ]]; then
	echo "usage: simple latency(ms) bandwidth(Mbit)"
	exit 1
fi

echo "delay $1ms rate $2Mbit"

tc qdisc add dev eth0 root netem delay $1ms rate $2Mbit
tc qdisc add dev eth1 root netem delay $1ms rate $2Mbit
